spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shower?characterEncoding=UTF-8&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: neo
    password: IAMneo
  #redis配置
  redis:
    host: 101.35.163.229
    password: IAMneo
    database: 0
    port: 6379


mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启二级缓存
    cache-enabled: true


server:
  port: 3200